//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAuthentication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormAuthenticationEntities : DbContext
    {
        public FormAuthenticationEntities()
            : base("name=FormAuthenticationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_data> Student_data { get; set; }
        public virtual DbSet<login> login { get; set; }

        public System.Data.Entity.DbSet<FormAuthentication.Models.Information> Information { get; set; }
    }
}
